-- AlterTable
ALTER TABLE `notifications` MODIFY `type` ENUM('COMMENT_ON_POST', 'REPLY_TO_COMMENT', 'BLESSING_ON_POST', 'SONG_COPIED', 'BAND_INVITATION', 'BAND_INVITATION_ACCEPTED', 'BAND_INVITATION_REJECTED', 'PAYMENT_APPROVED', 'PAYMENT_REJECTED') NOT NULL;
